export interface Usuario {
   id_usuario?: number;
   nombre: string;
   correo: string;
   // Rol info comes joined usually, or we use id_rol_usuario
   rol?: string; // name
   id_rol_usuario?: number;
   id_usuario_estado?: number;
   id_usuario_publicador?: number;
   id_congregacion?: number; // Needed? Maybe not in basic list, but for editing if we support it.
   roles?: string[]; // Autogenerated/mapped
}

export interface UsuarioCreate {
   nombre: string;
   correo: string;
   contrasena: string;
   id_rol_usuario?: number;
   id_usuario_estado?: number;
   id_usuario_publicador?: number;
   // id_congregacion is not directly on user table, it's on publicador, 
   // BUT the user might want to filter/assign it. 
   // For now, let's assume Basic User Creation doesn't create a Publicador automatically unless linked.
}

export interface UsuarioUpdate {
   nombre?: string;
   correo?: string;
   contrasena?: string;
   id_rol_usuario?: number;
   id_usuario_estado?: number;
}
